# docker-compose.yml

version: '3.8'
services:

  postgres:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=codewithaymane
      - POSTGRES_PASSWORD=69566910Id@
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres: